// <auto-generated />
namespace bookweb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class aspnetusers2t_users1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aspnetusers2t_users1));
        
        string IMigrationMetadata.Id
        {
            get { return "201709130549077_aspnetusers2t_users1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
